name: Url Shortening Landing Page Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: npm install && npm run build

  unit-tests:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run Tests
        run: npm run test:watch

  deploy:
    needs: unit-tests
    runs-on: self-hosted

    steps:
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
